Repository ynput/ayon-aftereffects, pull requests merged in 2025-07, with the labels that each got.

#38 Changed auto_install default to True
  server/settings/main.py
Labels: type: maintenance

#39 use data['workfile_startup'] for workfile tool
  client/ayon_aftereffects/api/launch_logic.py
  client/ayon_aftereffects/hooks/pre_launch_args.py
Labels: type: enhancement, community

#41 Chore: Allow per project addon version
  package.py
Labels: type: enhancement
