Repository ynput/ayon-aftereffects, pull requests merged in 2025-03, with the labels that each got.

#21 Added collectors for compositions
  client/ayon_aftereffects/plugins/publish/extract_compositions.py
Labels: sponsored, type: feature

#28 Reduce legacy terminology
  client/ayon_aftereffects/api/README.md
  client/ayon_aftereffects/api/extension/jsx/hostscript.jsx
  client/ayon_aftereffects/api/launch_logic.py
  client/ayon_aftereffects/api/pipeline.py
  client/ayon_aftereffects/api/workfile_template_builder.py
  client/ayon_aftereffects/api/ws_stub.py
  client/ayon_aftereffects/plugins/load/load_background.py
  client/ayon_aftereffects/plugins/load/load_file.py
  client/ayon_aftereffects/plugins/publish/collect_extension_version.py
  client/ayon_aftereffects/plugins/publish/validate_scene_settings.py
  client/ayon_aftereffects/plugins/workfile_build/load_placeholder.py
Labels: type: enhancement, community

#26 Create Render: Do not enforce renaming of composition (defined by settings now) + allow multiple comps to target same product name
  client/ayon_aftereffects/plugins/create/create_render.py
  server/settings/creator_plugins.py
  server/settings/main.py
Labels: type: enhancement, community

#25 Workfile Builder: Template settings key `template_path` -> `path`
  server/settings/templated_workfile_build.py
  server/settings/workfile_builder.py
Labels: type: bug, community

#24 Code tweaks: Cosmetics + type hints
  client/ayon_aftereffects/plugins/publish/collect_render.py
  client/ayon_aftereffects/plugins/publish/collect_rendered_files.py
  client/ayon_aftereffects/plugins/publish/validate_instance_folder.py
Labels: type: enhancement, community

#23 Refactor `CollectWorkfile` to InstancePlugin
  client/ayon_aftereffects/plugins/publish/collect_workfile.py
Labels: type: enhancement, community

#22 Improve logging: Do not log AEItem in artist facing report, plus report item with debug log for could not find layer metadata
  client/ayon_aftereffects/api/ws_stub.py
  client/ayon_aftereffects/plugins/publish/validate_footage_items.py
Labels: type: enhancement, community

#27 Create Render: Set Comp settings based on task entity attributes instead of folder
  client/ayon_aftereffects/api/__init__.py
  client/ayon_aftereffects/api/lib.py
  client/ayon_aftereffects/plugins/create/create_render.py
  client/ayon_aftereffects/plugins/publish/validate_scene_settings.py
Labels: type: enhancement, community

#30 Create Render: Fix applying setting `force_setting_values`
  client/ayon_aftereffects/plugins/create/create_render.py
  server/settings/creator_plugins.py
Labels: type: bug, community

#31 Feature/mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  pyproject.toml
  uv.lock
Labels: type: feature
